### ISSUE TITLE
Sintaxis error line 102

### ISSUE THREAD

**Issue by orderorder** [enigma9o7/smlinux#10]
./smlinux: line 103: `         elif [ -f ~/"$REPO"/enhancements/60fps.patch ]; then'

The "#" in the lines before shows this error.

**Comment by enigma9o7** [comment]
my bad, sorry

**Comment by enigma9o7** [comment]
Fixed now, but explanation.

Last night I was having problems with 60fps patch on ex.  Thought I commented out hte lines that installed it, but apperantly messed that up.
