### ISSUE TITLE
Can't even use the script for some reason.

### ISSUE THREAD

**Issue by cdegh** [enigma9o7/smlinux#14]
I've used the script before on Pop-OS and it worked flawlessly. Fast forward to now, some months later, and I'm currently on a fresh install of Ubuntu, I see new instructions on the github page. I merely try to build with the default config setup and I run into this issue. Terminal output below:

> [1] Preparing Build environment...
> 
> [2] Checking Github for smlinux updates....
> Installing smlinux...
> Cloning into '/home/cde/.local/share/sm64pc'...
> remote: Enumerating objects: 54, done.
> remote: Counting objects: 100% (54/54), done.
> remote: Compressing objects: 100% (44/44), done.
> remote: Total 2363 (delta 36), reused 10 (delta 10), pack-reused 2309
> Receiving objects: 100% (2363/2363), 17.90 MiB | 11.04 MiB/s, done.
> Resolving deltas: 100% (1308/1308), done.
> mv: cannot move '/home/cde/.local/share/sm64pc/smlinux' to '/usr/local/sbin/smlinux': Permission denied
> WARNING: Could not write to first path directory. Creating /home/cde/bin.
> mkdir: cannot create directory ‘/home/cde/bin’: File exists
> Script Update Complete.
> No compatible sm64 configuration file found, game will create one.
> No compatible save file found.
> /home/cde/bin/smlinux: line 1812: syntax error: unexpected end of file

I go the extra mile and install a fresh copy of Linux Lite, copy and paste the bash command, try a default build, same issue. I even tried changing the basepath to ~/sm64pc but it seems like the config file was being ignored.Not sure what's with the permission errors. I didn't use sudo as was instructed NOT to do, and I literally installed linux on my laptop just to compile this, so no prior outlandish configuration was done. Confused, frustrated, hoping you can help.

Additionally, if I created the directory manually where it was trying to, it complains about autoupdate being set to 1 in the config file. When I set it to 0, the script then complains about autoupdate being set to 0 and recommends I set it to 1. It's actually sorta funny to me. 

EDIT: Oddly enough, SViN24's fork of your script works just fine for me currently. Even stranger, your script works just fine now when I ran it to update my build just now. I'm even more confused now.

**Comment by enigma9o7** [comment]
It was my fault completely, that syntax error line 1812.   I had made a minor change and didn't test it (bad idea) and had made a simple syntax mistake, and fixed it, so all good now.

**Comment by cdegh** [comment]
> It was my fault completely, that syntax error line 1812. I had made a minor change and didn't test it (bad idea) and had made a simple syntax mistake, and fixed it, so all good now.

Hi there enigma9o7! Good looking out! Testing the new script in a fresh Bunsenlabs install (I distrohop a lot) and all is well.
