### ISSUE TITLE
Cannot edit configuration anymore

### ISSUE THREAD

**Issue by WandeingLagomorph793** [enigma9o7/smlinux#22]
If I open smlinux and select config, It'll pop up with the usual configuration screen, but then if I select edit then it won't let me edit anything, neither from a GUI or from opening a text editor, instead it just tries building Mario 64 as if it were the first build, it seems to read from the config file itself just fine since some of the settings match, but otherwise it treats it as if it's building from scratch so I end up having to recompile the entire game and I can no longer edit the file from within the terminal.

**Comment by WandeingLagomorph793** [comment]
Update: Testing with smlinux after update showed *none* of the functionality working without it building from source, only fix for that was rebuilding from a fresh build entirely via the build option.

**Comment by enigma9o7** [comment]
I see you closed it, I hope that means its fixed.   

I recently implemented a user-submitted python based config file editor and some users had issues installing the required python modules (PyQt5 and numpy).  I believe I have now resolved this in the script, such that it's more likely to install the required dependencies correctly, and also correctly fall back to text editor like before if the python config GUI doesn't work.

If anyone is still having an issue with latest version please let me know.

**Comment by WandeingLagomorph793** [comment]
> I see you closed it, I hope that means its fixed.
> 
> I recently implemented a user-submitted python based config file editor and some users had issues installing the required python modules (PyQt5 and numpy). I believe I have now resolved this in the script, such that it's more likely to install the required dependencies correctly, and also correctly fall back to text editor like before if the python config GUI doesn't work.
> 
> If anyone is still having an issue with latest version please let me know.

It seemed to work after I rebuilt from scratch via it's top "Build" option, that might have been what it needed to install dependencies, at the time anyway, falling back to text editor is a good idea though, so it doesn't force rebuild from scratch every single time.
