### ISSUE TITLE
Please do NOT touch my .bashrc

### ISSUE THREAD

**Issue by ChristianSilvermoon** [enigma9o7/smlinux#23]
`smlinux` appears to create the folder `~/bin` and install itself there along with updating the `~/.bashrc` file to prepend `$PATH` with it.

I keep my copy of `smlinux` under `~/.local/bin`, which is *already* in my `$PATH`.

I would really appreciate it if `smlinux` accounted for the directory it is located in and did *not* create an additional folder in my home directory, or modify my `.bashrc`.

Pretty please prompt me, at least?

**Comment by enigma9o7** [comment]
Ok I think I implemented a fix.  Now during the first installation, it
should check if any of the commonly used path folders exist in your path,
and if so, use one.  It should only create ~/bin and add it to bashrc/zshrc
if you dont have anything already.

for folder in bin .local/bin .local/share/bin Applications/bin
Applications/.bin .bin .local/share/.bin .local/.bin
do
if [ ! `echo $PATH | grep "$HOME"/"$folder"` = "" ]; then
PATHDIR="$HOME"/"$folder"
return
fi
done
if [ ! -d "$HOME"/bin ]; then
mkdir "$HOME"/bin
fi
export PATH=$HOME/bin:$PATH
PATHDIR=$HOME/bin
touch "$HOME"/.smlinuxNopath
if [ -f "$HOME"/.bashrc ]; then
bluecho Adding $HOME/bin to bash path...
echo 'export PATH=$HOME/bin:$PATH' >>~/.bashrc
fi
if [ -f "$HOME"/.zshrc ]; then
bluecho Adding $HOME/bin to zsh path...
echo 'export PATH=$HOME/bin:$PATH' >>~/.zshrc
fi

**Comment by ChristianSilvermoon** [comment]
That seems ideal, thanks a million, though this actually had occurred on a run other than the first... and in the case of my `.zshrc`, it had been appended twice with the same line.

I don't use ZSH much, so it'd taken me much longer to notice. I don't know if that particular oddity reflects the current state of the project or if it was a quirk with an older verison I'd had at a previous time, however.

I don't know if that's related but it felt worth mentioning.
