### ISSUE TITLE
Problems with ztsd

### ISSUE THREAD

**Issue by improvised-explosive-device** [enigma9o7/smlinux#27]
Getting ````ModuleNotFoundError: No module named 'zstd'```` when compiling on Arch, all dependencies are installed. If I additionally install ztsd through pip, I get ````AttributeError: module 'zstd' has no attribute 'ZstdCompressor'````.

**Comment by enigma9o7** [comment]
I believe the problem you were having has been resolved upstream and should work now.  If this wasn't related to creating pak file for sm64nx, then please reopen this issue.  

https://github.com/teamsalta/sm64nx/commit/4a92e6c9382cf9201625321a7fcc3d140df20a9a
