### ISSUE TITLE
Don't upgrade gcc@9.3.0.1 on macOS Mojave !

### ISSUE THREAD

**Issue by allenginsberg** [enigma9o7/smlinux#32]
That version broke the script. To fix it you need to type on terminal this after you install the script to uninstall the latest version and downgrade to gcc-9.3.0:
1. "brew uninstall gcc@9"
2. "brew tap-new $USER/local-tap"
3. "brew extract --version=9.3.0 gcc@9 $USER/local-tap"
4. "brew install gcc@9.3.0"
And that's it !

Now you run the script and everything will be ok 👯

**Comment by enigma9o7** [comment]
Thanks!  I also modified script to install 9.3.0 in the first place for new users too.

Probably gunna switch bigsur to 10/latest and keep everytihng else frozen at 9.3.0.
