### ISSUE TITLE
updateconfig not working

### ISSUE THREAD

**Issue by devomaa** [enigma9o7/smlinux#34]

**Comment by coreybruce** [comment]
Need to give some sort of information to make a issue and show why the "updateconfig not working"

**Comment by enigma9o7** [comment]
The updateconfig function is supposed to notice if you have an old configfile, and if so update it to the currently used fields.  If it doesnt work right, then the python gui will fail (as its written in such a way that config file has to contain the fields it expects, and cant contain anything else) so it will revert to using text editor to edit config file.  smlinux script shouldn't care, only the python GUI it calls for config editor.  

Easiest solution (on user side) is run "smlinux reset" which gives you default config file.  

However if this function isn't working right for users, I would need some detail.
