### ISSUE TITLE
Linux: cannot create shortcuts,menu entry desktop file already exists but it doesn't

### ISSUE THREAD

**Issue by XRaTiX** [enigma9o7/smlinux#36]
I'm trying to compile sm64-coop,the game compiles successfully but it doesn't create shortcuts in the desktop nor in the .local/share/applications,I noticed that in the terminal it says menu entry desktop file already exists but it doesn't,I verify and it doesn't exist sm64-coop.desktop on .$HOME/.local/share/applications,I even try to compile sm64ex but same problem with the shortcuts.

If I can give more information about the problem feel free to ask.

**Comment by enigma9o7** [comment]
What OS and version do you use?

**Comment by XRaTiX** [comment]
I'm using Manjaro KDE,the latest version.

You can reproduce the issue on a live usb environment,i just tried the script on a Manjaro KDE live usb environment and Ubuntu 20.04 live usb environment,both says Menu entry desktop file already exists too.

**Comment by XRaTiX** [comment]
Thank you for the fix.

**Comment by enigma9o7** [comment]
I have not fixed anything yet, all I've done is look at the script and make
sure it seems right, I havent investigated further and had hoped to find
some time this weekend to do so.  Are you now saying it fixed itself?

**Comment by XRaTiX** [comment]
You not? I just tried again the latest commit and it creates the shortcut now

**Comment by XRaTiX** [comment]
I just tried the [commit](https://github.com/enigma9o7/smlinux/commit/b556906681b9adda8e31bb69fe92dc84f59c4c03) before you did the cleanup on the makedesktop,and indeed it doesn't work,so the cleanup really fixed it
