### ISSUE TITLE
Stuck at waiting for cleaner aesthetics

### ISSUE THREAD

**Issue by SandWoodJones** [enigma9o7/smlinux#37]
The script runs perfectly until it inevitably gets stuck right here
```console
Linking Render96 Models to Dynamic Options Model Loader...
Linking Old School HD Mario to Dynamic Options Model Loader...
Linking HD Bowser to Dynamic Options Model Loader...
Build Succesful!
[7] Checking shortcuts...
Menu entry desktop file already exists.
Waiting for Cleaner Aesthetics texture pack to finish downloading...
```
If it really takes that long to download Cleaner Aesthetics, maybe add some user feedback? But I don't think that's the problem as what stands out to me is this part of the script:
```sh
	bluecho Waiting for Cleaner Aesthetics texture pack to finish downloading...
	while [ ! -d "$SMLINUX"/Cleaner-Aesthetics/gfx/textures ] # dont put a semicolon here
do
	sleep 1
done
```
Maybe sleeping interrupts the download or something

**Comment by enigma9o7** [comment]
How long did you wait?  Their repo is about ~120MB iirc so shouldn't be too
long of a wait, depending on how fast your computier is (how much time
already elapsed during build) and how fast your internet is.

That code you found is exactly what it appears to be, waiting to see when
it shows up.  The download was started earlier in the script (when it said
"Starting cleaner aesthetics texture download") in the background, and
won't be affected by whatever script is doing (including sleep), all script
is doing there is checking if its done or not.

**Comment by SandWoodJones** [comment]
Downloading it on my browser took about 30 seconds, I've waited definitively up to 10 minutes on the script. Is there any way for me to just place the downloaded zip somewhere and the script taking care of the rest?

**Comment by enigma9o7** [comment]
I'll try to debug later to see what could be going wrong, I dunno.  But you
can just put in in res manually (like installing any texture pack as
describedon faq) or if you want smlinux to do it for you it is waiting for
it to appear in that folder you mentioned earlier, ~/.local/share/smlinux
whatever path

**Comment by enigma9o7** [comment]
Ok I think I resolved this.  This was in fact an error I introduced when rearranging things to support sm64plus.
