### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by HiImBlahh** [enigma9o7/smlinux#38]
The new app that got installed is not opening. is there another way to start the game besides the app?

**Comment by HiImBlahh** [comment]
nvm i installed menulibre and made a new launcher

**Comment by HiImBlahh** [comment]
> I'm guessing macOS? What version?

chrome os. i am using chromebook's linux

**Comment by enigma9o7** [comment]
What do you mean by another way to start the game besides the app.  What do you mean the app?  Isn't the application you're talking about sm64, which is the game?  If by the app you mean sm64, then no, there is no way to start sm64 without starting sm64????

Chromebook is not something I have experience with.  If you want to help me figure out how to create shortcuts for chromebook, tell me how they work.  The method smlinux uses follows xdg spec which pretty much every desktop environment follows to some extent.... and surprising if chromebook's linux doesn't.

**Comment by HiImBlahh** [comment]
> What do you mean by another way to start the game besides the app. What do you mean the app? Isn't the application you're talking about sm64, which is the game? If by the app you mean sm64, then no, there is no way to start sm64 without starting sm64????
> 
> Chromebook is not something I have experience with. If you want to help me figure out how to create shortcuts for chromebook, tell me how they work. The method smlinux uses follows xdg spec which pretty much every desktop environment follows to some extent.... and surprising if chromebook's linux doesn't.

i'm saying the app wont start and i was asking if there was another way to start the app. but i found another way so i closed this issue
