### ISSUE TITLE
help

### ISSUE THREAD

**Issue by HiImBlahh** [enigma9o7/smlinux#39]
![Screenshot 2021-05-20 9 32 50 AM](https://user-images.githubusercontent.com/78574005/119016165-7e26ed00-b94e-11eb-8950-1eacd52ec181.png)

**Comment by HiImBlahh** [comment]
why garry's mod missing texture

**Comment by enigma9o7** [comment]
Sorry what is garry's mod?  Anyways I'm not familiar with every mod, probably best contacting garry.

**Comment by HiImBlahh** [comment]
> Sorry what is garry's mod? Anyways I'm not familiar with every mod, probably best contacting garry.

it's a game, and those black and purple things looks like garry's mod missing texture. The port i builded was sm64plus

**Comment by HiImBlahh** [comment]
it's fixed! all i had to do was run `smlinux purge` and then build sm64plus again. but i didn't like it because it was laggy and i couldn't change the controls so i ran `smlinux purge` again.  i am building render96ex at this moment.

**Comment by enigma9o7** [comment]
Purge deltes EVERYTHING, including all the files smlinux downloaded, your config file, every add-on model/texture/patch etc it ever downloaded.  You should not ever need to do this.  If you wanted to delete sm64plus, just delete sm64plus folder.  But anyways no worries.
